export * from './auth.service';
import { AuthService } from './auth.service';
export * from './backup.service';
import { BackupService } from './backup.service';
export * from './custom-templates.service';
import { CustomTemplatesService } from './custom-templates.service';
export * from './docker.service';
import { DockerService } from './docker.service';
export * from './edge.service';
import { EdgeService } from './edge.service';
export * from './edge-groups.service';
import { EdgeGroupsService } from './edge-groups.service';
export * from './edge-jobs.service';
import { EdgeJobsService } from './edge-jobs.service';
import { EdgeStacksService } from './edge-stacks.service';
export * from './edge-templates.service';
import { EdgeTemplatesService } from './edge-templates.service';
export * from './endpoint-groups.service';
import { EndpointGroupsService } from './endpoint-groups.service';
import { EndpointsService } from './endpoints.service';
export * from './gitops.service';
import { GitopsService } from './gitops.service';
export * from './helm.service';
import { HelmService } from './helm.service';
export * from './intel.service';
import { IntelService } from './intel.service';
export * from './kubernetes.service';
import { KubernetesService } from './kubernetes.service';
export * from './ldap.service';
import { LdapService } from './ldap.service';
export * from './motd.service';
import { MotdService } from './motd.service';
export * from './rbac-enabled.service';
import { RbacEnabledService } from './rbac-enabled.service';
export * from './registries.service';
import { RegistriesService } from './registries.service';
export * from './resource-controls.service';
import { ResourceControlsService } from './resource-controls.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './ssl.service';
import { SslService } from './ssl.service';
export * from './stacks.service';
import { StacksService } from './stacks.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './system.service';
import { SystemService } from './system.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './team-memberships.service';
import { TeamMembershipsService } from './team-memberships.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './templates.service';
import { TemplatesService } from './templates.service';
export * from './upload.service';
import { UploadService } from './upload.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './webhooks.service';
import { WebhooksService } from './webhooks.service';
export * from './websocket.service';
import { WebsocketService } from './websocket.service';
export const APIS = [AuthService, BackupService, CustomTemplatesService, DockerService, EdgeService, EdgeGroupsService, EdgeJobsService, EdgeStacksService, EdgeTemplatesService, EndpointGroupsService, EndpointsService, GitopsService, HelmService, IntelService, KubernetesService, LdapService, MotdService, RbacEnabledService, RegistriesService, ResourceControlsService, RolesService, SettingsService, SslService, StacksService, StatusService, SystemService, TagsService, TeamMembershipsService, TeamsService, TemplatesService, UploadService, UsersService, WebhooksService, WebsocketService];
